'use strict';

// ============================================================
//  Bibliothèque des formules disponibles (FR)
//  Compatible Google Sheets / Excel via HyperFormula
//  Séparateur d'arguments : ; (point-virgule)
// ============================================================

const FORMULA_CATEGORIES = {
  maths:     { label: 'Mathématiques', icon: '∑', color: '#4f7cff' },
  logique:   { label: 'Logique',       icon: '?', color: '#22c55e' },
  compt:     { label: 'Comptage',      icon: '#', color: '#fbbf24' },
  recherche: { label: 'Recherche',     icon: '🔍', color: '#7c3aed' },
  texte:     { label: 'Texte',         icon: 'T', color: '#f97316' },
  date:      { label: 'Date & heure',  icon: '📅', color: '#06b6d4' },
  stats:     { label: 'Statistiques',  icon: 'σ', color: '#ec4899' },
  info:      { label: 'Information',   icon: 'ℹ', color: '#94a3b8' },
};

const FORMULAS = [
  // ───── Mathématiques ─────
  { name:'SOMME', en:'SUM', cat:'maths',
    sig:'SOMME(valeur1; [valeur2; ...])',
    short:'Somme des valeurs',
    desc:"Renvoie la somme de tous les arguments numériques. Ignore les cellules vides et les textes.",
    example:'=SOMME(palettes_entree)' },
  { name:'SOMME.SI', en:'SUMIF', cat:'maths',
    sig:'SOMME.SI(plage; critère; [plage_somme])',
    short:'Somme conditionnelle',
    desc:'Additionne les cellules qui répondent à un critère.',
    example:'=SOMME.SI(client;"BBA Emballages";palettes_entree)' },
  { name:'SOMME.SI.ENS', en:'SUMIFS', cat:'maths',
    sig:'SOMME.SI.ENS(plage_somme; plage_crit1; crit1; [plage_crit2; crit2; ...])',
    short:'Somme multi-critères',
    desc:"Additionne les cellules qui répondent à plusieurs critères.",
    example:'=SOMME.SI.ENS(palettes_entree;client;"BBA Emballages";date;">01/12/2025")' },
  { name:'SOMMEPROD', en:'SUMPRODUCT', cat:'maths',
    sig:'SOMMEPROD(plage1; plage2; ...)',
    short:'Somme des produits',
    desc:'Multiplie les plages élément par élément, puis additionne le tout.',
    example:'=SOMMEPROD(km;litres)' },
  { name:'MOYENNE', en:'AVERAGE', cat:'maths',
    sig:'MOYENNE(valeur1; [valeur2; ...])',
    short:'Moyenne arithmétique',
    desc:'Renvoie la moyenne des arguments numériques.',
    example:'=MOYENNE(palettes_entree)' },
  { name:'MOYENNE.SI', en:'AVERAGEIF', cat:'maths',
    sig:'MOYENNE.SI(plage; critère; [plage_moyenne])',
    short:'Moyenne conditionnelle',
    desc:'Moyenne des cellules qui répondent à un critère.',
    example:'=MOYENNE.SI(client;"EUROTAB";palettes_entree)' },
  { name:'MOYENNE.SI.ENS', en:'AVERAGEIFS', cat:'maths',
    sig:'MOYENNE.SI.ENS(plage_moy; plage_crit1; crit1; ...)',
    short:'Moyenne multi-critères',
    desc:'Moyenne avec plusieurs critères simultanés.',
    example:'=MOYENNE.SI.ENS(palettes_entree;client;"BBA*";date;">01/01/2025")' },
  { name:'MIN', en:'MIN', cat:'maths',
    sig:'MIN(valeur1; [valeur2; ...])',
    short:'Plus petite valeur',
    desc:'Renvoie le minimum.',
    example:'=MIN(palettes_entree)' },
  { name:'MAX', en:'MAX', cat:'maths',
    sig:'MAX(valeur1; [valeur2; ...])',
    short:'Plus grande valeur',
    desc:'Renvoie le maximum.',
    example:'=MAX(palettes_entree)' },
  { name:'PRODUIT', en:'PRODUCT', cat:'maths',
    sig:'PRODUIT(valeur1; [valeur2; ...])',
    short:'Produit des valeurs',
    desc:'Multiplie tous les arguments.',
    example:'=PRODUIT(2;3;4)' },
  { name:'ARRONDI', en:'ROUND', cat:'maths',
    sig:'ARRONDI(nombre; chiffres)',
    short:'Arrondit un nombre',
    desc:'Arrondit au nombre de chiffres décimaux indiqué.',
    example:'=ARRONDI(3,14159;2)  → 3,14' },
  { name:'ARRONDI.SUP', en:'ROUNDUP', cat:'maths',
    sig:'ARRONDI.SUP(nombre; chiffres)',
    short:'Arrondi supérieur',
    desc:'Arrondit toujours vers le haut.',
    example:'=ARRONDI.SUP(3,1;0)  → 4' },
  { name:'ARRONDI.INF', en:'ROUNDDOWN', cat:'maths',
    sig:'ARRONDI.INF(nombre; chiffres)',
    short:'Arrondi inférieur',
    desc:'Arrondit toujours vers le bas.',
    example:'=ARRONDI.INF(3,9;0)  → 3' },
  { name:'ENT', en:'INT', cat:'maths',
    sig:'ENT(nombre)',
    short:'Partie entière',
    desc:"Tronque vers l'entier inférieur.",
    example:'=ENT(8,9)  → 8' },
  { name:'ABS', en:'ABS', cat:'maths',
    sig:'ABS(nombre)',
    short:'Valeur absolue',
    desc:'Renvoie le nombre sans signe.',
    example:'=ABS(-12,5)  → 12,5' },
  { name:'RACINE', en:'SQRT', cat:'maths',
    sig:'RACINE(nombre)',
    short:'Racine carrée',
    desc:'Renvoie la racine carrée d\'un nombre positif.',
    example:'=RACINE(16)  → 4' },
  { name:'PUISSANCE', en:'POWER', cat:'maths',
    sig:'PUISSANCE(nombre; puissance)',
    short:'Élévation à la puissance',
    desc:'Renvoie nombre^puissance.',
    example:'=PUISSANCE(2;10)  → 1024' },
  { name:'MOD', en:'MOD', cat:'maths',
    sig:'MOD(nombre; diviseur)',
    short:'Modulo (reste division)',
    desc:'Renvoie le reste de la division.',
    example:'=MOD(10;3)  → 1' },
  { name:'PI', en:'PI', cat:'maths',
    sig:'PI()',
    short:'Constante π',
    desc:'Renvoie 3,14159265358979...',
    example:'=PI()*RACINE(2)' },
  { name:'ALEA', en:'RAND', cat:'maths',
    sig:'ALEA()',
    short:'Nombre aléatoire 0-1',
    desc:'Renvoie un nombre aléatoire entre 0 et 1.',
    example:'=ALEA()' },
  { name:'ALEA.ENTRE.BORNES', en:'RANDBETWEEN', cat:'maths',
    sig:'ALEA.ENTRE.BORNES(min; max)',
    short:'Aléatoire entier entre bornes',
    desc:'Entier aléatoire entre min et max inclus.',
    example:'=ALEA.ENTRE.BORNES(1;100)' },
  { name:'SOUS.TOTAL', en:'SUBTOTAL', cat:'maths',
    sig:'SOUS.TOTAL(no_fonction; plage)',
    short:'Sous-total',
    desc:'Calcule un sous-total (1=MOYENNE, 2=NB, 9=SOMME, etc.) en ignorant les cellules masquées.',
    example:'=SOUS.TOTAL(9;palettes_entree)' },

  // ───── Logique ─────
  { name:'SI', en:'IF', cat:'logique',
    sig:'SI(condition; valeur_si_vrai; [valeur_si_faux])',
    short:'Test conditionnel',
    desc:"Renvoie une valeur si la condition est vraie, une autre sinon.",
    example:'=SI(palettes_entree>300;"GROS";"petit")' },
  { name:'SI.CONDITIONS', en:'IFS', cat:'logique',
    sig:'SI.CONDITIONS(cond1; val1; cond2; val2; ...)',
    short:'Multi-conditions imbriquées',
    desc:'Évalue plusieurs conditions et renvoie la première qui est vraie.',
    example:'=SI.CONDITIONS(A1<10;"petit";A1<100;"moyen";VRAI;"gros")' },
  { name:'SI.MULTIPLE', en:'SWITCH', cat:'logique',
    sig:'SI.MULTIPLE(expression; cas1; val1; [cas2; val2; ...]; [défaut])',
    short:'Switch / Aiguillage',
    desc:'Compare une expression à une liste de valeurs et renvoie la première qui correspond.',
    example:'=SI.MULTIPLE(operation;"ENTREE";1;"SORTIE";-1;0)' },
  { name:'SIERREUR', en:'IFERROR', cat:'logique',
    sig:'SIERREUR(valeur; valeur_si_erreur)',
    short:'Capture les erreurs',
    desc:"Renvoie la valeur si elle ne génère pas d'erreur, sinon la valeur de remplacement.",
    example:'=SIERREUR(A1/B1;0)' },
  { name:'SI.NON.DISP', en:'IFNA', cat:'logique',
    sig:'SI.NON.DISP(valeur; valeur_si_na)',
    short:'Capture le #N/A',
    desc:'Comme SIERREUR mais uniquement pour #N/A.',
    example:'=SI.NON.DISP(RECHERCHEV(...);"Inconnu")' },
  { name:'ET', en:'AND', cat:'logique',
    sig:'ET(condition1; [condition2; ...])',
    short:'ET logique',
    desc:'Renvoie VRAI si toutes les conditions sont vraies.',
    example:'=ET(A1>0;A1<100)' },
  { name:'OU', en:'OR', cat:'logique',
    sig:'OU(condition1; [condition2; ...])',
    short:'OU logique',
    desc:'Renvoie VRAI si au moins une condition est vraie.',
    example:'=OU(client="EUROTAB";client="WEISS")' },
  { name:'NON', en:'NOT', cat:'logique',
    sig:'NON(condition)',
    short:'Négation logique',
    desc:'Inverse VRAI/FAUX.',
    example:'=NON(ESTVIDE(A1))' },
  { name:'OUEX', en:'XOR', cat:'logique',
    sig:'OUEX(condition1; condition2; ...)',
    short:'OU exclusif',
    desc:'Vrai si un nombre impair de conditions sont vraies.',
    example:'=OUEX(A1>0;B1>0)' },
  { name:'VRAI', en:'TRUE', cat:'logique',
    sig:'VRAI()',
    short:'Constante VRAI',
    desc:'Renvoie la valeur logique VRAI.',
    example:'=VRAI()' },
  { name:'FAUX', en:'FALSE', cat:'logique',
    sig:'FAUX()',
    short:'Constante FAUX',
    desc:'Renvoie la valeur logique FAUX.',
    example:'=FAUX()' },

  // ───── Comptage ─────
  { name:'NB', en:'COUNT', cat:'compt',
    sig:'NB(valeur1; [valeur2; ...])',
    short:'Compte les nombres',
    desc:'Compte les cellules qui contiennent un nombre.',
    example:'=NB(palettes_entree)' },
  { name:'NBVAL', en:'COUNTA', cat:'compt',
    sig:'NBVAL(valeur1; [valeur2; ...])',
    short:'Compte les non-vides',
    desc:'Compte les cellules non vides (texte ou nombre).',
    example:'=NBVAL(client)' },
  { name:'NB.VIDE', en:'COUNTBLANK', cat:'compt',
    sig:'NB.VIDE(plage)',
    short:'Compte les vides',
    desc:'Compte les cellules vides.',
    example:'=NB.VIDE(productivite)' },
  { name:'NB.SI', en:'COUNTIF', cat:'compt',
    sig:'NB.SI(plage; critère)',
    short:'Comptage conditionnel',
    desc:'Compte les cellules qui répondent à un critère.',
    example:'=NB.SI(client;"BBA Emballages")' },
  { name:'NB.SI.ENS', en:'COUNTIFS', cat:'compt',
    sig:'NB.SI.ENS(plage1; crit1; [plage2; crit2; ...])',
    short:'Comptage multi-critères',
    desc:'Compte selon plusieurs critères simultanés.',
    example:'=NB.SI.ENS(client;"BBA*";palettes_entree;">100")' },

  // ───── Recherche ─────
  { name:'RECHERCHEV', en:'VLOOKUP', cat:'recherche',
    sig:'RECHERCHEV(valeur_cherchée; tableau; n°_colonne; [valeur_proche])',
    short:'Recherche verticale',
    desc:"Cherche une valeur dans la 1ʳᵉ colonne d'un tableau et renvoie la valeur d'une autre colonne sur la même ligne. FAUX = correspondance exacte.",
    example:'=RECHERCHEV("MAT";code:productivite;7;FAUX)' },
  { name:'RECHERCHEH', en:'HLOOKUP', cat:'recherche',
    sig:'RECHERCHEH(valeur; tableau; n°_ligne; [valeur_proche])',
    short:'Recherche horizontale',
    desc:'Comme RECHERCHEV mais en cherchant dans la 1ʳᵉ ligne.',
    example:'=RECHERCHEH("date";A1:Z1;5;FAUX)' },
  { name:'INDEX', en:'INDEX', cat:'recherche',
    sig:'INDEX(plage; n°_ligne; [n°_colonne])',
    short:'Valeur à une position',
    desc:'Renvoie la valeur située à l\'intersection de la ligne et de la colonne.',
    example:'=INDEX(client;5)  → 5e élément' },
  { name:'EQUIV', en:'MATCH', cat:'recherche',
    sig:'EQUIV(valeur_cherchée; plage; [type])',
    short:'Position d\'une valeur',
    desc:'Renvoie la position d\'une valeur dans une plage. Type=0 → exact.',
    example:'=EQUIV("EUROTAB";client;0)' },
  { name:'DECALER', en:'OFFSET', cat:'recherche',
    sig:'DECALER(référence; lignes; colonnes; [hauteur]; [largeur])',
    short:'Référence décalée',
    desc:"Renvoie une référence décalée d'un nombre de lignes/colonnes.",
    example:'=DECALER(A1;2;3)' },
  { name:'INDIRECT', en:'INDIRECT', cat:'recherche',
    sig:'INDIRECT(texte_référence)',
    short:'Référence depuis texte',
    desc:"Construit une référence à partir d'une chaîne.",
    example:'=INDIRECT("A"&5)  ≡  =A5' },
  { name:'ADRESSE', en:'ADDRESS', cat:'recherche',
    sig:'ADRESSE(ligne; colonne; [type_abs])',
    short:'Construit une adresse',
    desc:'Renvoie l\'adresse texte d\'une cellule.',
    example:'=ADRESSE(5;3)  → "$C$5"' },
  { name:'LIGNE', en:'ROW', cat:'recherche',
    sig:'LIGNE([référence])',
    short:'Numéro de ligne',
    desc:'Renvoie le numéro de ligne.',
    example:'=LIGNE(A5)  → 5' },
  { name:'COLONNE', en:'COLUMN', cat:'recherche',
    sig:'COLONNE([référence])',
    short:'Numéro de colonne',
    desc:'Renvoie le numéro de colonne.',
    example:'=COLONNE(C1)  → 3' },
  { name:'CHOISIR', en:'CHOOSE', cat:'recherche',
    sig:'CHOISIR(n°_index; valeur1; [valeur2; ...])',
    short:'Choisit dans une liste',
    desc:'Renvoie le n-ième élément.',
    example:'=CHOISIR(2;"A";"B";"C")  → "B"' },

  // ───── Texte ─────
  { name:'CONCATENER', en:'CONCATENATE', cat:'texte',
    sig:'CONCATENER(texte1; [texte2; ...])',
    short:'Concatène des textes',
    desc:'Assemble plusieurs chaînes en une seule.',
    example:'=CONCATENER(client;" - ";date)' },
  { name:'CONCAT', en:'CONCAT', cat:'texte',
    sig:'CONCAT(texte1; [texte2; ...])',
    short:'Concatène (accepte plages)',
    desc:'Comme CONCATENER mais accepte des plages.',
    example:'=CONCAT(client)' },
  { name:'JOINDRE.TEXTE', en:'TEXTJOIN', cat:'texte',
    sig:'JOINDRE.TEXTE(séparateur; ignorer_vide; texte1; ...)',
    short:'Joint avec séparateur',
    desc:'Concatène en intercalant un séparateur.',
    example:'=JOINDRE.TEXTE(", ";VRAI;client)' },
  { name:'GAUCHE', en:'LEFT', cat:'texte',
    sig:'GAUCHE(texte; [n_caractères])',
    short:'n caractères à gauche',
    desc:'Extrait les premiers caractères.',
    example:'=GAUCHE("BBA Emballages";3)  → "BBA"' },
  { name:'DROITE', en:'RIGHT', cat:'texte',
    sig:'DROITE(texte; [n_caractères])',
    short:'n caractères à droite',
    desc:'Extrait les derniers caractères.',
    example:'=DROITE("EG-598-FF";2)  → "FF"' },
  { name:'STXT', en:'MID', cat:'texte',
    sig:'STXT(texte; n°_départ; n_caractères)',
    short:'Sous-chaîne',
    desc:'Extrait n caractères à partir de la position indiquée (1-indexée).',
    example:'=STXT("EG-598-FF";4;3)  → "598"' },
  { name:'NBCAR', en:'LEN', cat:'texte',
    sig:'NBCAR(texte)',
    short:'Longueur du texte',
    desc:'Compte les caractères.',
    example:'=NBCAR(client)' },
  { name:'MAJUSCULE', en:'UPPER', cat:'texte',
    sig:'MAJUSCULE(texte)',
    short:'Tout en MAJUSCULES',
    desc:'Convertit en majuscules.',
    example:'=MAJUSCULE("hello")  → "HELLO"' },
  { name:'MINUSCULE', en:'LOWER', cat:'texte',
    sig:'MINUSCULE(texte)',
    short:'Tout en minuscules',
    desc:'Convertit en minuscules.',
    example:'=MINUSCULE("HELLO")  → "hello"' },
  { name:'NOMPROPRE', en:'PROPER', cat:'texte',
    sig:'NOMPROPRE(texte)',
    short:'Initiales En Majuscule',
    desc:"Met une majuscule à chaque mot.",
    example:'=NOMPROPRE("jean dupont")  → "Jean Dupont"' },
  { name:'SUPPRESPACE', en:'TRIM', cat:'texte',
    sig:'SUPPRESPACE(texte)',
    short:'Supprime espaces inutiles',
    desc:'Retire les espaces superflus.',
    example:'=SUPPRESPACE("  abc  ")  → "abc"' },
  { name:'REMPLACER', en:'REPLACE', cat:'texte',
    sig:'REMPLACER(ancien_texte; n°_départ; n_caractères; nouveau_texte)',
    short:'Remplace par position',
    desc:'Remplace un nombre de caractères à partir d\'une position.',
    example:'=REMPLACER("ABCDEF";2;3;"XY")  → "AXYEF"' },
  { name:'SUBSTITUE', en:'SUBSTITUTE', cat:'texte',
    sig:'SUBSTITUE(texte; ancien; nouveau; [n°_occurrence])',
    short:'Substitue partout',
    desc:'Remplace toutes les occurrences (ou seulement la n-ième).',
    example:'=SUBSTITUE(date;"/";"-")' },
  { name:'TROUVE', en:'FIND', cat:'texte',
    sig:'TROUVE(texte_cherché; texte; [n°_départ])',
    short:'Position (sensible casse)',
    desc:'Renvoie la position. Sensible à la casse.',
    example:'=TROUVE("BBA";client)' },
  { name:'CHERCHE', en:'SEARCH', cat:'texte',
    sig:'CHERCHE(texte_cherché; texte; [n°_départ])',
    short:'Position (insensible casse)',
    desc:'Comme TROUVE mais insensible à la casse, accepte * et ?.',
    example:'=CHERCHE("bba";client)' },
  { name:'TEXTE', en:'TEXT', cat:'texte',
    sig:'TEXTE(valeur; format)',
    short:'Formate en texte',
    desc:'Convertit un nombre/date en texte selon un format.',
    example:'=TEXTE(date;"DD/MM/YYYY")' },
  { name:'CTXT', en:'FIXED', cat:'texte',
    sig:'CTXT(nombre; [décimales]; [sans_séparateur])',
    short:'Nombre vers texte formaté',
    desc:'Convertit un nombre en texte avec décimales.',
    example:'=CTXT(1234,567;2)  → "1 234,57"' },
  { name:'CNUM', en:'VALUE', cat:'texte',
    sig:'CNUM(texte)',
    short:'Texte vers nombre',
    desc:'Convertit un texte numérique en nombre.',
    example:'=CNUM("123,45")  → 123,45' },
  { name:'REPT', en:'REPT', cat:'texte',
    sig:'REPT(texte; n)',
    short:'Répète n fois',
    desc:'Répète une chaîne.',
    example:'=REPT("-";10)' },
  { name:'CAR', en:'CHAR', cat:'texte',
    sig:'CAR(code)',
    short:'Caractère depuis code',
    desc:'Renvoie le caractère du code Unicode.',
    example:'=CAR(65)  → "A"' },
  { name:'CODE', en:'CODE', cat:'texte',
    sig:'CODE(texte)',
    short:'Code Unicode',
    desc:'Renvoie le code Unicode du 1er caractère.',
    example:'=CODE("A")  → 65' },
  { name:'EXACT', en:'EXACT', cat:'texte',
    sig:'EXACT(texte1; texte2)',
    short:'Comparaison stricte',
    desc:'VRAI si les deux textes sont identiques (sensible à la casse).',
    example:'=EXACT("ABC";"abc")  → FAUX' },

  // ───── Date & heure ─────
  { name:'AUJOURDHUI', en:'TODAY', cat:'date',
    sig:'AUJOURDHUI()',
    short:"Date du jour",
    desc:"Renvoie la date d'aujourd'hui (sans heure).",
    example:'=AUJOURDHUI()' },
  { name:'MAINTENANT', en:'NOW', cat:'date',
    sig:'MAINTENANT()',
    short:'Date + heure courantes',
    desc:'Date et heure actuelles.',
    example:'=MAINTENANT()' },
  { name:'DATE', en:'DATE', cat:'date',
    sig:'DATE(année; mois; jour)',
    short:'Construit une date',
    desc:'Crée une date à partir des composants.',
    example:'=DATE(2025;12;31)' },
  { name:'ANNEE', en:'YEAR', cat:'date',
    sig:'ANNEE(date)',
    short:"Année d'une date",
    desc:'Extrait l\'année.',
    example:'=ANNEE(date)' },
  { name:'MOIS', en:'MONTH', cat:'date',
    sig:'MOIS(date)',
    short:'Mois (1-12)',
    desc:'Extrait le mois.',
    example:'=MOIS(date)' },
  { name:'JOUR', en:'DAY', cat:'date',
    sig:'JOUR(date)',
    short:'Jour du mois (1-31)',
    desc:'Extrait le jour.',
    example:'=JOUR(date)' },
  { name:'HEURE', en:'HOUR', cat:'date',
    sig:'HEURE(date_heure)',
    short:'Heure (0-23)',
    desc:"Extrait l'heure.",
    example:'=HEURE(MAINTENANT())' },
  { name:'MINUTE', en:'MINUTE', cat:'date',
    sig:'MINUTE(date_heure)',
    short:'Minutes (0-59)',
    desc:'Extrait les minutes.',
    example:'=MINUTE(MAINTENANT())' },
  { name:'SECONDE', en:'SECOND', cat:'date',
    sig:'SECONDE(date_heure)',
    short:'Secondes (0-59)',
    desc:'Extrait les secondes.',
    example:'=SECONDE(MAINTENANT())' },
  { name:'JOURSEM', en:'WEEKDAY', cat:'date',
    sig:'JOURSEM(date; [type])',
    short:'Jour de la semaine',
    desc:'1 = dimanche par défaut. Type 2 = lundi=1.',
    example:'=JOURSEM(date;2)' },
  { name:'NO.SEMAINE', en:'WEEKNUM', cat:'date',
    sig:'NO.SEMAINE(date; [type])',
    short:'N° de semaine',
    desc:'Numéro de semaine ISO.',
    example:'=NO.SEMAINE(date;21)' },
  { name:'DATEDIF', en:'DATEDIF', cat:'date',
    sig:'DATEDIF(date_début; date_fin; unité)',
    short:'Différence entre dates',
    desc:'Unité : "Y"=années, "M"=mois, "D"=jours.',
    example:'=DATEDIF(date1;date2;"D")' },
  { name:'NB.JOURS', en:'DAYS', cat:'date',
    sig:'NB.JOURS(date_fin; date_début)',
    short:'Nombre de jours',
    desc:'Différence en jours.',
    example:'=NB.JOURS(date2;date1)' },
  { name:'NB.JOURS.OUVRES', en:'NETWORKDAYS', cat:'date',
    sig:'NB.JOURS.OUVRES(date_début; date_fin; [jours_fériés])',
    short:'Jours ouvrés (lun-ven)',
    desc:'Compte les jours ouvrés entre 2 dates.',
    example:'=NB.JOURS.OUVRES(date1;date2)' },
  { name:'FIN.MOIS', en:'EOMONTH', cat:'date',
    sig:'FIN.MOIS(date_départ; n_mois)',
    short:'Dernier jour du mois +/- n',
    desc:'Renvoie le dernier jour du mois décalé.',
    example:'=FIN.MOIS(date;0)' },
  { name:'TEMPS', en:'TIME', cat:'date',
    sig:'TEMPS(heure; minute; seconde)',
    short:'Construit une heure',
    desc:'Crée une valeur horaire.',
    example:'=TEMPS(14;30;0)' },

  // ───── Statistiques ─────
  { name:'ECARTYPE', en:'STDEV', cat:'stats',
    sig:'ECARTYPE(valeur1; [valeur2; ...])',
    short:'Écart-type (échantillon)',
    desc:"Estimation de l'écart-type sur un échantillon.",
    example:'=ECARTYPE(palettes_entree)' },
  { name:'ECARTYPEP', en:'STDEVP', cat:'stats',
    sig:'ECARTYPEP(valeur1; [valeur2; ...])',
    short:'Écart-type (population)',
    desc:'Écart-type calculé sur la population entière.',
    example:'=ECARTYPEP(palettes_entree)' },
  { name:'VAR', en:'VAR', cat:'stats',
    sig:'VAR(valeur1; [valeur2; ...])',
    short:'Variance (échantillon)',
    desc:"Variance d'un échantillon.",
    example:'=VAR(palettes_entree)' },
  { name:'MEDIANE', en:'MEDIAN', cat:'stats',
    sig:'MEDIANE(valeur1; [valeur2; ...])',
    short:'Médiane',
    desc:'Valeur centrale.',
    example:'=MEDIANE(palettes_entree)' },
  { name:'MODE', en:'MODE', cat:'stats',
    sig:'MODE(valeur1; [valeur2; ...])',
    short:'Valeur la plus fréquente',
    desc:'Mode statistique.',
    example:'=MODE(client)' },
  { name:'RANG', en:'RANK', cat:'stats',
    sig:'RANG(valeur; plage; [ordre])',
    short:'Rang dans une plage',
    desc:'Position de la valeur (ordre=0 décroissant, 1 croissant).',
    example:'=RANG(A1;palettes_entree;0)' },
  { name:'CENTILE', en:'PERCENTILE', cat:'stats',
    sig:'CENTILE(plage; k)',
    short:'k-ième centile',
    desc:'k entre 0 et 1. CENTILE(plage;0,5) = médiane.',
    example:'=CENTILE(palettes_entree;0,9)' },
  { name:'QUARTILE', en:'QUARTILE', cat:'stats',
    sig:'QUARTILE(plage; quart)',
    short:'Quartile (0=min, 4=max)',
    desc:'Renvoie un quartile (0/1/2/3/4).',
    example:'=QUARTILE(palettes_entree;3)' },
  { name:'GRANDE.VALEUR', en:'LARGE', cat:'stats',
    sig:'GRANDE.VALEUR(plage; k)',
    short:'k-ième plus grande',
    desc:'GRANDE.VALEUR(plage;1) = MAX.',
    example:'=GRANDE.VALEUR(palettes_entree;3)' },
  { name:'PETITE.VALEUR', en:'SMALL', cat:'stats',
    sig:'PETITE.VALEUR(plage; k)',
    short:'k-ième plus petite',
    desc:'PETITE.VALEUR(plage;1) = MIN.',
    example:'=PETITE.VALEUR(palettes_entree;3)' },

  // ───── Information ─────
  { name:'ESTVIDE', en:'ISBLANK', cat:'info',
    sig:'ESTVIDE(valeur)',
    short:'Cellule vide ?',
    desc:'VRAI si la cellule est vide.',
    example:'=SI(ESTVIDE(A1);"vide";"plein")' },
  { name:'ESTNUM', en:'ISNUMBER', cat:'info',
    sig:'ESTNUM(valeur)',
    short:'Est un nombre ?',
    desc:'VRAI si la valeur est numérique.',
    example:'=ESTNUM(palettes_entree)' },
  { name:'ESTTEXTE', en:'ISTEXT', cat:'info',
    sig:'ESTTEXTE(valeur)',
    short:'Est du texte ?',
    desc:'VRAI si la valeur est du texte.',
    example:'=ESTTEXTE(client)' },
  { name:'ESTLOGIQUE', en:'ISLOGICAL', cat:'info',
    sig:'ESTLOGIQUE(valeur)',
    short:'Est VRAI/FAUX ?',
    desc:'VRAI pour une valeur booléenne.',
    example:'=ESTLOGIQUE(VRAI)' },
  { name:'ESTERREUR', en:'ISERROR', cat:'info',
    sig:'ESTERREUR(valeur)',
    short:'Est une erreur ?',
    desc:'VRAI si la valeur est une erreur.',
    example:'=SI(ESTERREUR(A1/B1);0;A1/B1)' },
  { name:'ESTNA', en:'ISNA', cat:'info',
    sig:'ESTNA(valeur)',
    short:'Est #N/A ?',
    desc:'VRAI uniquement si #N/A.',
    example:'=ESTNA(RECHERCHEV(...))' },
  { name:'TYPE', en:'TYPE', cat:'info',
    sig:'TYPE(valeur)',
    short:'Type de la valeur',
    desc:'1=nombre, 2=texte, 4=logique, 16=erreur.',
    example:'=TYPE(A1)' },
  { name:'NA', en:'NA', cat:'info',
    sig:'NA()',
    short:'Renvoie #N/A',
    desc:'Force la valeur d\'erreur #N/A.',
    example:'=SI(A1<0;NA();A1)' },
];

// Index par nom pour recherche rapide
const FORMULAS_BY_NAME = Object.fromEntries(FORMULAS.map((f) => [f.name, f]));
const FORMULAS_BY_EN = Object.fromEntries(FORMULAS.map((f) => [f.en, f]));
